### ISSUE TITLE
Label categories and artists nodes

### ISSUE THREAD

**Issue by garoff** [TheArtificial/theartificial.nl#37]
To do :
- categories labels - always show
- artists labels - display or hide to be implemented with the existing label button.
- artists labels - when all artists labels are hidden, show artist label if corresponding node is hovered.

**Comment by gerwitz** [comment]
Here's an example of the "normal" way: http://bl.ocks.org/mbostock/950642 … note that the results of `.enter()` are assigned to a variable `node` so the originally-appended _g_ can have both _image_ and _text_ appended within. (In this case, you probably want _circle_ and _text_.)

**Comment by gerwitz** [comment]
Here's a much fancier example (from Moritz!) that has labels "orbit" their nodes by using a second force layout: http://bl.ocks.org/MoritzStefaner/1377729
