### ISSUE TITLE
Create feeds

### ISSUE THREAD

**Issue by shannonethomas** [TheArtificial/theartificial.nl#55]
Create an all-feeds page that holds all things Artificial.
- blog posts
  - title
  - preview img
  - author
  - date
  - description (contents)
- case studies
  - title
  - preview image
  - date
- cocktails
  - title
  - author (mixologist)
  - date
  - preview image (gif)
- to [icon] series
  - preview (automagically created)
  - series title
  - author
  - date
- FTFY
  - title
  - author
  - date
  - preview img

![theartificial_feed](https://cloud.githubusercontent.com/assets/1819919/18436517/0e854360-78f9-11e6-9a5e-4c31157310f1.png)
![theartificial_about_person](https://cloud.githubusercontent.com/assets/1819919/18436616/9fd7ce00-78f9-11e6-94c6-2def822f1d62.png)

**Comment by gerwitz** [comment]
This and search should align, so it'd be nice to render these cards client-side. Maybe using Handlebars templates.

This means we need a standard structure for these preview cards, and to align feed pages and the search store. Maybe the search store can be re-used?

**Comment by gerwitz** [comment]
I'm aligning the cards for pre-rendering and client-side rendering with Mustache templates.

Current status: hidden search is working, with blog posts, cocktails, and ftfy results.

**Comment by gerwitz** [comment]
As of b13a6c2be54d2c5350f28ca83da2cee797341925 everything except icon series is included, though these URLs are not linked to:
https://theartificial.com/search/
https://theartificial.com/search/feed.html

**Comment by gerwitz** [comment]
You've listed icon series previews as "automagically created"…

This implies they are generated on toicon.com and pulled into theartificial.com by client scripting. This would guarantee they're up-to-date, but prevent searching for them. And it's hard to do right.

If we have them as "hidden" parts of theartificial.com, though, we can't auto-generate them and will need to figure out where to store the previews (or at least icon SVGs).

**Comment by gerwitz** [comment]
@shannonethomas Does the master feed appear anywhere in navigation?

**Comment by shannonethomas** [comment]
no

**Comment by gerwitz** [comment]
In that case, this is "done" except for #70, #71, #72, #73
