### ISSUE TITLE
Update blog styles

### ISSUE THREAD

**Issue by shannonethomas** [TheArtificial/theartificial.nl#56]
Include preview images. If no preview image exists, include preview text.

![theartificial_blog](https://cloud.githubusercontent.com/assets/1819919/18436688/e9f06b64-78f9-11e6-88dd-7b479f477da5.png)

**Comment by shannonethomas** [comment]
Also add the curated bit up top.

**Comment by gerwitz** [comment]
Depends on #22

**Comment by gerwitz** [comment]
Are these preview images always the same as the masthead, or can they be thumbnails in a different ratio?

If the latter, are they to be generated from the masthead (with some minimal "from left, center, or right" art direction) or a distinct prepared asset?

(I assume that any post without a specified preview would just use the whole masthead.)
