### ISSUE TITLE
Blog preview images on /feeds/ page

### ISSUE THREAD

**Issue by shannonethomas** [TheArtificial/theartificial.nl#68]
Fix blog preview images on /feeds/ page

<img width="1058" alt="screen shot 2018-02-12 at 17 19 40" src="https://user-images.githubusercontent.com/1819919/36106948-f3569d60-1018-11e8-9f70-04695e6c92c4.png">

**Comment by gerwitz** [comment]
Resolved by ac4bffb5e3f86ae3d4bfa5a3ec8ccc786803538f
